apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-docker-registry-data
  namespace: docker-registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: k8s-docker-registry-data
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi